config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to:'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :favorites, only: [:create, :destroy]
  resources :posts do
    collection do
      post :confirm
    end
  end
  resources :users do
    member do
      get :favorite_list
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader

  validates :title,  presence: true
  validates :content,  presence: true
  validates :image,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  before_validation { email.downcase! }
  has_secure_password
  mount_uploader :image, ImageUploader

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
  has_many :posts, foreign_key: :user_id, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  include SessionsHelper

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんの投稿をお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to posts_path, notice: "#{favorite.post.user.name}さんの投稿をお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all.order(id: "DESC")
  end

  def show
    @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def confirm
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    render :new if @post.invalid?
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      ContactMailer.contact_mail(@post).deliver
      if @post.save
        format.html { redirect_to @post, notice: '投稿が完了しました！' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: '投稿が更新されました！' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: '投稿を削除しました。' }
      format.json { head :no_content }
    end
  end

  private
  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :image, :content, :user_id, :image_cache)
  end

  def authenticate_user
    @post = Post.find(params[:id])
    unless current_user.id == @post.user.id
      flash[:notice] = "他のインフルエンサーの削除、編集はできないよ！"
      redirect_to posts_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :favorite_list]
  before_action :check_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all.order(id: "DESC")
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'ユーザー登録が完了です！ログイン画面に進んでください！' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'ユーザー情報が更新されました！' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'ユーザーが削除されました。' }
      format.json { head :no_content }
    end
  end

  def favorite_list
    @favorites = current_user.favorite_posts.all
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end

  # def correct_user
  #   user = User.find(params[:id])
  #   if current_user != user
  #     redirect_to posts_path
  #   end
  # end

  def check_user
    @user = User.find(params[:id])
  unless current_user.id == @user.id
    flash[:notice] = "他のInfluencerは削除と編集できないよ！"
    redirect_to users_path
  end
end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user?(user)
    current_user.id == user.id
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm' || action_name == 'create'
      confirm_posts_path
    elsif action_name == 'edit'
      post_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <div class="header">
      <% if logged_in? %>
        <%= link_to "プロフィール", user_path(current_user.id) %>
        <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <% else %>
        <%= link_to "新規会員登録", new_user_path %>
        <%= link_to "ログインページへ", new_session_path %>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, url: choose_new_or_edit) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "箇所") %> 登録内容にエラーがあります。</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :タイトル %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :イメージ %><br />
    <%= image_tag(@post.image.url) if @post.image && @post.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :投稿内容 %>
    <%= form.text_field :content %>
  </div>

  <div class="actions">
    <div class="decide">
    <%= form.submit "この内容で投稿する"%>
    </div>
  </div>
<% end %>

app/views/posts/confirm.html.erb
<h1>以下の内容で投稿しますか？</h1>
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.hidden_field :image_cache %>
  <div class="confirm">
    <p>タイトル：<%= @post.title %></p>
    <p>内容：<%= @post.content %></p>
    <p>イメージ：<%= image_tag @post.image.to_s %></p>
    <div class ="confirm_footer">
        <%= form.submit  "これで登録する" %>
        <%= form.submit "はじめに戻る" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>投稿内容を編集中</h1>

<%= render 'form', post: @post %>

<div class="footer">
  <%= link_to '詳細を確認する', @post %>
  <%= link_to '投稿一覧へ進む', posts_path %>
</div>

app/views/posts/index.html.erb
<h1>InstaApps</h1>

<table>
  <div class="user_thead">
    <thead>
      <tr>
        <th>タイトル</th>
        <th>内容</th>
        <th>ユーザーID</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  </div>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.user_id %></td>
        <td><%= image_tag post.image.to_s %></td>
        <td><%= link_to '詳細をみる', post %></td>
        <% if @user == current_user %>
          <td><%= link_to '編集する', edit_post_path(post) %></td>
          <td><%= link_to '削除する', post, method: :delete, data: { confirm: '本当に削除して良いですか?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="footer">
  <%= link_to '新規投稿する', new_post_path %>
</div>

app/views/posts/new.html.erb
<h1>新規投稿</h1>

<%= render 'form', post: @post %>

<div class="footer">
  <%= link_to '投稿一覧に進む', posts_path %>
</div>

app/views/posts/show.html.erb
<h1>
  <strong>投稿内容はコチラ</strong>
</h1>

<p>
  <strong>タイトル：</strong>
  <%= @post.title %>
</p>

<p>
  <strong>投稿内容：</strong>
  <%= @post.content %>
</p>

<p>
  <strong>ユーザーID：</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>イメージ：</strong>
  <%= image_tag @post.image.to_s %>
</p>

<div class= favorite_button>
  <% unless @post.user_id == current_user.id %>
    <% if @favorite.present? %>
      <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
    <% else %>
      <%= link_to 'お気に入りする', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
    <% end %>
  <% else %>
    <div class="footer">
      <%= link_to '編集する', edit_post_path(@post) %>
      <%= link_to '削除する', post_path(@post.id), method: :delete, data: {confirm: '本当に削除してもよろしいですか?'}%>
      <%= link_to '投稿一覧へ進む', posts_path %>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "箇所") %> 登録内容にエラーがあります。</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :イメージ %><br />
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <div class="decide">
    <%= f.submit "この内容で会員登録する" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー編集中</h1>

<%= render 'form', user: @user %>

<div class="footer">
  <%= link_to '詳細を確認する', @user %>
  <%= link_to '戻る', users_path %>
</div>

app/views/users/favorite_list.html.erb
<h1>お気に入りの投稿一覧</h1>

<div class="favorite_list">
  <% @favorites.each do |favorlite| %>
    <div class="favorlite_page_image_area">
      <%= link_to post_path(favorlite) do %>
        <%= image_tag favorlite.image.url %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Influesers</h1>

  <table>
    <thead>
      <tr>
        <th>イメージ</th>
        <th>名前</th>
        <th>メールアドレス</th>
        <th>パスワード</th>
        <th></th>
      </tr>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td class="a"><%= image_tag user.image.to_s %></td>
          <td class="b"><%= user.name %></td>
          <td class="c"><%= user.email %></td>
          <td class="d"><%= user.password_digest %></td>
          <td class="e"><%= link_to '詳細', user %></td>
          <td class="f"><%= link_to '編集', edit_user_path(user) %></td>
          <td class="g"><%= link_to '削除', user, method: :delete %></td>
        </tr>

      <% end %>
    </tbody>
  </table>
</div>

<br>
<div class="footer">
  <%= link_to '新規ユーザーはコチラ', new_user_path %>
</div>

app/views/users/new.html.erb
<h1>新規会員登録</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1>
  <strong><%= @user.name %>のページ</strong>
</h1>

<p>
  <strong>プロフィール画像</strong>
  <%= image_tag @user.image.to_s %>
</p>

<p>
  <strong>メールアドレス：</strong>
  <%= @user.email %>
</p>

<p>
  <strong>パスワード：</strong>
  <%= @user.password_digest %>
</p>

<div class="footer">
  <%= link_to '新規投稿に進む', new_post_path %>
    <% if @user == current_user %>
      <%= link_to 'ユーザー編集をする', edit_user_path(@user) %>
      <%= link_to 'お気に入り一覧はコチラ', favorite_list_user_path(@user) %>
    <% end %>
  <%= link_to 'ユーザーリストに進む', users_path %>
  <%= link_to '投稿一覧に進む', posts_path %>
</div>